---
output:
  md_document:
    variant: markdown_github
    pandoc_args:
      - --atx-headers
---

## 4.4 単回帰

```{r setup, message=FALSE}
library(rstan)
library(ggplot2)
library(ggmcmc)
```

```{r}
d <- read.csv("RStanBook/chap04/input/data-salary.txt")
```

```{r}
head(d)
```

### 4.4.2 データの分布の確認

```{r}
ggplot(d, aes(x = X, y = Y)) +
  geom_point()
```

### 4.4.4 Rのlm関数で推定

```{r}
res_lm <- lm(Y ~ X, data = d)
res_lm
```

```{r}
X_new <- data.frame(X = 23:60)
conf_95 <- predict(res_lm, X_new, interval = 'confidence', level = 0.95)
pred_95 <- predict(res_lm, X_new, interval = 'prediction', level = 0.95)
```

信頼区間

```{r}
conf_95_df <- data.frame(X_new, conf_95)

ggplot() +
  geom_ribbon(data = conf_95_df, aes(x = X, ymin = lwr, ymax = upr), alpha = 0.2) +
  geom_line(data = conf_95_df, aes(x = X, y = fit)) +
  geom_point(data = d, aes(x = X, y = Y))
```

予測区間

```{r}
pred_95_df <- data.frame(X_new, pred_95)

ggplot() +
  geom_ribbon(data = pred_95_df, aes(x = X, ymin = lwr, ymax = upr), alpha = 0.2) +
  geom_line(data = pred_95_df, aes(x = X, y = fit)) +
  geom_point(data = d, aes(x = X, y = Y))
```

### 4.4.5 Stanで実装

model4-5.stan

```{r echo=FALSE, comment=''}
cat(readLines("RStanBook/chap04/model/model4-5.stan"), sep = "\n")
```

### 4.4.6 Rからの実行方法

```{r cache=TRUE, results="hide", message=FALSE}
data <- list(N = nrow(d), X = d$X, Y = d$Y)
fit <- stan(file = "RStanBook/chap04/model/model4-5.stan", data = data, seed = 1234)
```

### 4.4.7 RStanの結果の見方

```{r}
fit
```

### 4.4.8 収束診断をファイルに出力する

```{r}
ggs_traceplot(ggs(fit, inc_warmup = TRUE, stan_include_auxiliar = TRUE))
```

### 4.4.9 MCMCの設定の変更

```{r eval=FALSE}
stanmodel <- stan_model(file = "RStanBook/chap04/model/model4-5.stan")

fit <- sampling(
  stanmodel,
  data = data,
  pars = c("b", "sigma"),
  init = function() {
    list(a = runif(1, -10, 10), b = runif(1, 0, 10), sigma = 10)
  },
  seed = 123,
  chains = 3, iter = 1000, warmup = 200, thin = 2)
```

### 4.4.10 並列計算の実行方法

```{r eval=FALSE}
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

### 4.4.11 ベイズ信頼区間とベイズ予測区間の算出

```{r}
ms <- rstan::extract(fit)
```

```{r}
head(ms$b)
quantile(ms$b, probs = c(0.025, 0.975))
```

```{r}
d_mcmc <- as.data.frame(ms)[1:3]
head(d_mcmc)
```

```{r}
ggplot(d_mcmc, aes(x = a, y = b)) +
  geom_point(shape = 1, alpha = 0.2)
```

50歳の人の基本年収の分布と年収の予測分布

```{r}
N_mcmc <- length(ms$lp__)
y50_base <- ms$a + ms$b * 50
y50 <- rnorm(n = N_mcmc, mean = y50_base, sd = ms$sigma)
d_mcmc <- data.frame(a = ms$a, b = ms$b, sigma = ms$sigma, y50_base, y50)
```

### 4.4.12 transformed parametersブロックとgenerated quantitiesブロック

model4-4.stan

```{r echo=FALSE, comment=''}
cat(readLines("RStanBook/chap04/model/model4-4.stan"), sep = "\n")
```

```{r cache=TRUE, results="hide", message=FALSE}
X_new <- 23:60
data <- list(N = nrow(d), X = d$X, Y = d$Y, N_new = length(X_new), X_new = X_new)
fit <- stan(file = "RStanBook/chap04/model/model4-4.stan", data = data, seed = 1234)
ms <- rstan::extract(fit)
```

```{r}
head(ms$y_new[, 1:4])
```
