---
output:
  md_document:
    variant: markdown_github
    pandoc_args:
      - --atx-headers
---

## 5.1 重回帰

```{r setup, message=FALSE}
library(rstan)
library(ggplot2)
library(GGally)
library(ggmcmc)
library(dplyr)
```

```{r}
d <- read.csv("RStanBook/chap05/input/data-attendance-1.txt")
```

```{r}
head(d)
```

### 5.1.2 データの分布の確認

```{r message=FALSE}
d %>% mutate(A = as.factor(A)) %>% ggpairs
```

### 5.1.5 Stanで実装

model5-3.stan

```{r echo=FALSE, comment=''}
cat(readLines("RStanBook/chap05/model/model5-3.stan"), sep = "\n")
```

### 5.1.6 データのスケーリング

```{r cache=TRUE, results="hide", message=FALSE}
data <- list(N = nrow(d), A = d$A, Score = d$Score / 200, Y = d$Y)
fit <- stan(file = "RStanBook/chap05/model/model5-3.stan", data = data, seed = 1234)
```

### 5.1.7 推定結果の解釈

```{r}
fit %>% capture.output %>% head(10) %>% cat(sep = "\n")
```

### 5.1.8 図によるモデルのチェック

```{r}
ms <- rstan::extract(fit)
d_qua <- t(apply(ms$y_pred, 2, quantile, prob = c(0.1, 0.5, 0.9)))
colnames(d_qua) <- c("p10", "p50", "p90")
d_qua <- data.frame(d, d_qua)
d_qua$A <- as.factor(d_qua$A)

ggplot(data = d_qua, aes(x = Y, y = p50, ymin = p10, ymax = p90, shape = A, fill = A)) +
  coord_fixed(ratio = 1, xlim = c(0, 0.5), ylim = c(0, 0.5)) +
  geom_pointrange() +
  geom_abline(aes(slope = 1, intercept = 0), alpha = 0.6, linetype = "31") +
  scale_shape_manual(values = c(21, 24)) +
  scale_fill_manual(values = c("white", "grey70")) +
  labs(x = "Observed", y = "Predicted")
```

```{r}
N_mcmc <- length(ms$lp__)

d_noise <- data.frame(t(-t(ms$mu) + d$Y))
colnames(d_noise) <- paste0("noise", 1:nrow(d))

d_mode <- data.frame(t(apply(d_noise, 2, function(x) {
  dens <- density(x)
  mode_i <- which.max(dens$y)
  mode_x <- dens$x[mode_i]
  mode_y <- dens$y[mode_i]
  c(mode_x, mode_y)
})))
colnames(d_mode) <- c("X", "Y")

s_dens <- density(ms$s)
s_MAP <- s_dens$x[which.max(s_dens$y)]
bw <- 0.01

ggplot(data = d_mode, aes(x = X)) +
  geom_histogram(binwidth = bw, color = "black", fill = "white") +
  stat_function(fun = function(x) nrow(d) * bw * dnorm(x, mean = 0, sd = s_MAP), linetype = "dashed") +
  labs(x = "value", y = "count") +
  xlim(range(density(d_mode$X)$x))
```

## 5.2 二項ロジスティック回帰

```{r}
d <- read.csv("RStanBook/chap05/input/data-attendance-2.txt")
```

```{r}
d %>% head
```

### 5.2.2 データの分布の確認

```{r message=FALSE}
d %>%
  select(-1) %>%
  mutate(A = as.factor(A), ratio = Y / M) %>%
  ggpairs
```
