---
output:
  github_document:
    md_extensions: "+ignore_line_breaks"
    pandoc_args: "--atx-headers"
---

# 第2章 1つの変数の記述統計

## 2.4 データの視覚的表現

```{r}
指導法 <- c("C","B","B","A","B","C","A","D","D","D","A", "A","A","C","B","D","C","C","B","D")
```

```{r}
table(指導法)
```

```{r}
心理学テスト <- c(13,14,7,12,10,6,8,15,4,14,9,6,10,12,5,12,8,8,12,15)
```

```{r}
hist(心理学テスト)
```

## 2.5 平均とは

```{r}
テストa <- c(10,13,8,15,8)
```

```{r}
sum(テストa) / length(テストa)
```

```{r}
mean(テストa)
```

## 2.6 平均以外の代表値

```{r}
median(テストa)
```

```{r}
table(テストa)
```

最頻値は8

## 2.8 分散、標準偏差とは

```{r}
テストa平均 <- mean(テストa)
テストa平均
```

```{r}
平均からの偏差 <- テストa - テストa平均
平均からの偏差
```

```{r}
平均からの偏差の二乗 <- 平均からの偏差^2
平均からの偏差の二乗
```

```{r}
平均からの偏差の二乗和 <- sum(平均からの偏差の二乗)
平均からの偏差の二乗和
```

標本分散

```{r}
データ数 <- length(テストa)

分散 <- 平均からの偏差の二乗和 / データ数
分散
```

標準偏差

```{r}
sqrt(分散)
```

不偏分散

```{r}
var(テストa)
```

## 2.9 分散、標準偏差以外の散布度

平均偏差

```{r}
mean(abs(テストa - mean(テストa)))
```

範囲(レンジ)

```{r}
max(テストa) - min(テストa)
```

## 2.10 標準化

```{r}
心理学平均 <- mean(心理学テスト)
心理学平均
```

```{r}
心理学標準偏差 <- sqrt(mean((心理学テスト - 心理学平均)^2))
心理学標準偏差
```

```{r}
心理学z得点 <- (心理学テスト - 心理学平均) / 心理学標準偏差
心理学z得点
```

```{r}
心理学z得点平均 <- mean(心理学z得点)
心理学z得点平均
```

```{r}
心理学z得点標準偏差 <- sqrt(mean((心理学z得点 - 心理学z得点平均)^2))
心理学z得点標準偏差
```

## 2.11 偏差値

```{r}
心理学偏差値 <- 10 * 心理学z得点 + 50
心理学偏差値
```
