---
output:
  github_document:
    md_extensions: "+ignore_line_breaks"
    pandoc_args: "--atx-headers"
---

# 第6章 2つの平均値を比較する

## 6.2 独立な2群のt検定

```{r}
統計1男 <- c(6,10,6,10,5,3,5,9,3,3)
統計1女 <- c(11,6,11,9,7,5,8,7,7,9)
プール標準偏差 <- sqrt(((length(統計1男)-1)*var(統計1男)+(length(統計1女)-1)*var(統計1女)) / (length(統計1男)+length(統計1女)-2))
プール標準偏差
```

```{r}
t統計量 <- (mean(統計1男)-mean(統計1女)) / (プール標準偏差*sqrt(1/length(統計1男)+1/length(統計1女)))
t統計量
```

p値

```{r}
2*pt(-1.842885,18)
```

```{r}
t.test(統計1男,統計1女,var.equal=TRUE)
```

## 6.3 t検定の前提条件

分散の等質性

```{r}
クラスA <- c(54, 55, 52, 48, 50, 38, 41, 40, 53, 52)
クラスB <- c(67, 63, 50, 60, 61, 69, 43, 58, 36, 29)
var.test(クラスA, クラスB)
```

Welchの検定

```{r}
t.test(クラスA, クラスB, var.equal=FALSE)
```

## 6.4 対応のあるt検定

```{r}
統計テスト1 <- c(6,10,6,10,5,3,5,9,3,3,11,6,11,9,7,5,8,7,7,9)
統計テスト2 <- c(10,13,8,15,8,6,9,10,7,3,18,14,18,11,12,5,7,12,7,7)
変化量 <- 統計テスト2 - 統計テスト1
```

```{r}
t統計量 <- mean(変化量) / (sd(変化量)/sqrt(length(変化量)))
t統計量
qt(0.025,19,lower.tail=FALSE)
```

```{r}
t.test(統計テスト1,統計テスト2,paired=TRUE)
```

## 練習問題

\(1)

```{r}
統計好き <- c(6,10,6,10,11,6,11,7)
統計嫌い <- c(5,3,5,9,3,3,9,5,8,7,7,9)
var.test(統計好き,統計嫌い)
```

\(2)

```{r}
心理男 <- c(13,14,7,12,10,6,8,15,4,14)
心理女 <- c(9,6,10,12,5,12,8,8,12,15)
var.test(心理男,心理女)
```

\(3)

```{r}
参加前 <- c(61,50,41,55,51,48,46,55,65,70)
参加後<- c(59,48,33,54,47,52,38,50,64,63)
t.test(参加後,参加前,paired=TRUE)
```
