---
output:
  github_document:
    md_extensions: "+ignore_line_breaks"
    pandoc_args: "--atx-headers"
---

# 第5章 統計的仮説検定

## 5.3 標準正規分布を用いた検定

```{r}
心理学テスト <- c(13,14,7,12,10,6,8,15,4,14,9,6,10,12,5,12,8,8,12,15)
Z統計量 <- (mean(心理学テスト)-12) / sqrt(10/length(心理学テスト))
Z統計量
```

```{r}
qnorm(0.025)
qnorm(0.025,lower.tail=FALSE)
```

```{r}
curve(dnorm(x),-3,3)
abline(v=qnorm(0.025))
abline(v=qnorm(0.975))
```

p値を求める

```{r}
2*pnorm(2.828427,lower.tail=FALSE)
```

有意水準0.05よりも小さいので、帰無仮説は棄却される。

## 5.4 t分布を用いた検定

```{r}
t統計量 <- (mean(心理学テスト)-12) / sqrt(var(心理学テスト)/length(心理学テスト))
t統計量
```

p値

```{r}
2*pt(2.616648,19,lower.tail=FALSE)
```

```{r}
t.test(心理学テスト,mu=12)
```

## 5.5 相関係数の検定

```{r}

統計テスト1 <- c(6,10,6,10,5,3,5,9,3,3,11,6,11,9,7,5,8,7,7,9)
統計テスト2 <- c(10,13,8,15,8,6,9,10,7,3,18,14,18,11,12,5,7,12,7,7)
```

```{r}
標本相関 <- cor(統計テスト1, 統計テスト2)
サンプルサイズ <- length(統計テスト1)
t統計量 <- 標本相関*sqrt(サンプルサイズ-2) / sqrt(1-標本相関^2)
t統計量
```

p値

```{r}
2*pt(4.805707,18,lower.tail=FALSE)
```

## 5.6 独立性の検定

```{r}
数学 <- c("嫌い","嫌い","好き","好き","嫌い","嫌い","嫌い","嫌い","嫌い","好き","好き","嫌い","好き","嫌い","嫌い","好き","嫌い","嫌い","嫌い","嫌い")
統計 <- c("好き","好き","好き","好き","嫌い","嫌い","嫌い","嫌い","嫌い","嫌い","好き","好き","好き","嫌い","好き","嫌い","嫌い","嫌い","嫌い","嫌い")
table(数学,統計)
```

```{r}
期待度数 <- c(12*14/20, 12*6/20, 8*14/20, 8*6/20)
観測度数 <- c(10,2,4,4)
カイ二乗 <- sum((観測度数-期待度数)^2/期待度数)
カイ二乗
```

p値

```{r}
pchisq(2.539683,1,lower.tail=FALSE)
```

## 5.7 サンプルサイズの検定結果への影響について

```{r}
履修A <- matrix(c(16,12,4,8),2,2,
                dimnames=list(c("文系","理系"),c("履修した", "履修しない")))
履修A
```

独立性の検定

```{r}
chisq.test(履修A,correct=FALSE)
```

人数を10倍にする

```{r}
履修B <- 履修A * 10
履修B
chisq.test(履修B,correct=FALSE)
```

サンプルサイズが大きくなると、検定の結果は有意になりやすい

## 練習問題

\(1)

```{r}
height <- c(165,150,170,168,159,170,167,178,155,159,
            161,162,166,171,155,160,168,172,155,167)
t.test(height, mu = 170)
```

\(2)

```{r}
時間 <- c(1,3,10,12,6,3,8,4,1,5)
テスト <- c(20,40,100,80,50,50,70,50,10,60)
```

```{r}
cor.test(時間, テスト)
```

\(3)

```{r}
cor.test(時間, テスト, method="spearman")
```

```{r}
cor.test(時間, テスト, method="kendall")
```

\(4)

```{r}
和洋 <- c("洋食","和食","和食","洋食","和食","洋食","洋食","和食","洋食","洋食",
          "和食","洋食","和食","洋食","和食","和食","洋食","洋食","和食","和食")
甘辛 <- c("甘党","辛党","甘党","甘党","辛党","辛党","辛党","辛党","甘党","甘党",
          "甘党","甘党","辛党","辛党","甘党","辛党","辛党","甘党","辛党","辛党")

クロス集計 <- table(和洋, 甘辛)
chisq.test(クロス集計, correct=FALSE)
```

\(5)

```{r}
国語 <- c(60,40,30,70,55)
社会 <- c(80,25,35,70,50)
cor.test(国語, 社会)
```

```{r}
国語2 <- rep(国語, 2)
社会2 <- rep(社会, 2)
cor.test(国語2, 社会2)
```
